version: "3.7"

services:
  flexget:
    image: anthonyguerreiro/my-flexget
    depends_on:
      - transmission
    environment:
      - trakt_user=${trakt_user}
      - mal_user=${mal_user}
      - pushbullet_token=${pushbullet_token}
    volumes:
      - ${download_folder}:/downloads
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - ${download_folder}:/downloads
      - ${transmission_config_folder}:/config
      - ${transmission_watch_folder}:/watch
    restart: unless-stopped
